project:
  type: website

website:
  title: "loopy"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/billingross/loopy
  open-graph: true
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



