---
title: "Mind Blazer beckons"
format:
  html:
    code-fold: false
jupyter: python3
author: Paul Billing-Ross
date: 2025-07-21
---
# and the willing obey.

A strapping European man in a skimpy workout fit sits down next to me at the bar. "It looks we are a couple.", he offers with jockular enthusiasm. The synapses of my mind fan out in a wave, exploring the universe of unexpected possibilities reaching out in spacetime ahead of me. I hesitate for a moment to reflect on my decision to sit in a seat next to one already reserved. The bartended had registered my reticence when I approached the bar. "That one is open". Yes, but how open?

"Now it does". Being party to someone expressing their insecurities reminds me of seeing a cat walk in front of me and start to lick its own butthole. It is a normal and hygenic protocol for the cat and it also chose to do it in front of me. What role do I fill in the play of this cat? Does it feel some sense of shame or some hidden desire for intimacy? I wonder if shame is always tied to sex. Freud expressed that. Hold onto my ego while you perform your strange ritual and see that I am largely unphased by the experience. Now let me watch you remain visibly unharmed while I unfurl my freak flag so that I may release my freak sphincter.

# Welcome to my blog!
